version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=content
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: content
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

